APP_NAME = "answer-sheet"

A4_WIDTH_MM = 210.0
A4_HEIGHT_MM = 297.0

CONTENT_LEFT_MM = 20.0
CONTENT_RIGHT_MM = 190.0
CONTENT_WIDTH_MM = CONTENT_RIGHT_MM - CONTENT_LEFT_MM
TOP_MARGIN_MM = 18.0
BOTTOM_MARGIN_MM = 15.0

POSITION_MARK_OFFSET_MM = 10.0
POSITION_MARK_SIZE_MM = 6.0

HEADER_TITLE_HEIGHT_MM = 10.0
HEADER_GAP_MM = 6.0
STUDENT_INFO_HEIGHT_MM = 10.0
HEADER_SECTION_GAP_MM = 8.0

SECTION_TITLE_HEIGHT_MM = 8.0
TITLE_TO_CONTENT_GAP_MM = 4.0
SECTION_GAP_MM = 4.0

CHOICE_ROW_HEIGHT_MM = 6.0
CHOICE_OPTION_SPACING_MM = 6.0
CHOICE_NUMBER_WIDTH_MM = 6.0
CHOICE_CELL_GAP_MM = 4.0
CHOICE_BUBBLE_RADIUS_MM = 2.0

BLANK_LINE_HEIGHT_MM = 6.0
BLANK_QUESTION_GAP_MM = 3.0

CALCULATION_NUMBER_HEIGHT_MM = 5.0
CALCULATION_QUESTION_GAP_MM = 4.0
